
name: Go CI/CD

on:
  push:
    branches:
      - main

jobs:
  check-go-changes:
    name: Check Go Code Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Go code changes
        id: go_changes
        run: |
          if git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep -qE '\.go$'; then
            echo "Go code was modified, running tests..."
            echo "::set-output name=go_changed::true"
          else
            echo "No changes to Go code, skipping tests."
            echo "::set-output name=go_changed::false"
          fi

  check-existing-release:
    name: Check Existing Release
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null) || true
          if [ -z "$latest_tag" ]; then
            echo "No existing tags found."
            echo "::set-output name=existing_release::false"
          else
            echo "Existing release found: $latest_tag"
            echo "::set-output name=existing_release::true"
          fi

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [check-go-changes]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'  # Use the latest Go version

      - name: Run tests
        run: go test -v ./...

  build-binary:
    name: Build Binary and Release
    runs-on: ubuntu-latest
    needs: [test, check-existing-release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'  # Use the latest Go version

      - name: Build Binary
        run: go build

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null) || true
          if [ -z "$latest_tag" ]; then
            echo "No existing tags found."
            echo "::set-output name=existing_release::false"
            echo "::set-output name=release_tag::1.0.0"
          else
            echo "Existing release found: $latest_tag"
            echo "::set-output name=existing_release::true"
            echo "::set-output name=release_tag::$latest_tag"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.release_tag }}
          release_name: Release ${{ steps.get_latest_tag.outputs.release_tag }}
          body: Automated release from CI/CD.
          draft: false
          prerelease: false

  build-docker:
    name: Build Docker Container
    runs-on: ubuntu-latest
    needs: [build-binary]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'  # Use the latest Go version

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.get_latest_tag.outputs.release_tag }} .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.get_latest_tag.outputs.release_tag }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.get_latest_tag.outputs.release_tag }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        
